import 'package:hive/hive.dart';

/// One pending write waiting to reach the server: a weekly report, an
/// assignment submission, a progress update, a note, etc. Every module
/// that writes data while potentially offline goes through this queue
/// instead of calling Dio directly — see [OutboxQueue] for the drain
/// logic and `core/offline/sync_worker.dart` for when it runs.
///
/// [payloadType] tells the sync worker which repository's `syncOne()`
/// method to call for this item (see OutboxSyncHandler registration in
/// sync_worker.dart) — the queue itself doesn't know about HTTP.
class OutboxItem extends HiveObject {
  OutboxItem({
    required this.id,
    required this.payloadType,
    required this.payloadJson,
    required this.createdAt,
    this.attemptCount = 0,
    this.lastError,
    DateTime? nextRetryAt,
  }) : nextRetryAt = nextRetryAt ?? createdAt;

  final String id;
  final String payloadType;
  final Map<String, dynamic> payloadJson;
  final DateTime createdAt;
  int attemptCount;
  String? lastError;
  DateTime nextRetryAt;
}

/// Manual TypeAdapter — normally generated by build_runner, written here
/// by hand since this build was assembled without a Flutter/Dart SDK
/// available to run codegen. Verify field order/IDs still match if this
/// is regenerated later; typeId 1 must stay unique across the app's Hive
/// registrations (auth/course/etc. use 2, 3... — see main.dart).
class OutboxItemAdapter extends TypeAdapter<OutboxItem> {
  @override
  final int typeId = 1;

  @override
  OutboxItem read(BinaryReader reader) {
    final numFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numFields; i++) reader.readByte(): reader.read(),
    };
    return OutboxItem(
      id: fields[0] as String,
      payloadType: fields[1] as String,
      payloadJson: Map<String, dynamic>.from(fields[2] as Map),
      createdAt: DateTime.parse(fields[3] as String),
      attemptCount: fields[4] as int? ?? 0,
      lastError: fields[5] as String?,
      // Field 6 added in Week 3 for backoff scheduling; older cached
      // items written before this change won't have it, so fall back
      // to "retry now" rather than crash on a missing key.
      nextRetryAt: fields[6] != null ? DateTime.parse(fields[6] as String) : DateTime.now(),
    );
  }

  @override
  void write(BinaryWriter writer, OutboxItem obj) {
    writer
      ..writeByte(7)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.payloadType)
      ..writeByte(2)
      ..write(obj.payloadJson)
      ..writeByte(3)
      ..write(obj.createdAt.toIso8601String())
      ..writeByte(4)
      ..write(obj.attemptCount)
      ..writeByte(5)
      ..write(obj.lastError)
      ..writeByte(6)
      ..write(obj.nextRetryAt.toIso8601String());
  }
}

/// Known payload types — used as the discriminator when the sync worker
/// decides which repository to call.
class OutboxPayloadType {
  OutboxPayloadType._();
  static const weeklyReport = 'weekly_report';
  static const assignmentSubmission = 'assignment_submission';
  static const lessonProgress = 'lesson_progress';
  static const note = 'note';
}
